services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - app_network


  auth_service:
    build:
      context: ./back/auth_service
    container_name: auth-service
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DB_HOST: auth_db
      DB_PORT: 5432
      DB_NAME: auth_service_db
      DB_USER: auth_service_user
      DB_PASSWORD: password
      SECRET_KEY: $SECRET_KEY
      OAUTH_UID: $OAUTH_UID
      OAUTH_SECRET: $OAUTH_SECRET
    ports:
      - '8000:8000'
    volumes:
      - ./back/auth_service:/app
    networks:
      - app_network
    depends_on:
      redis:
        condition: service_started
      auth_db:
        condition: service_healthy

  auth_db:
    image: postgres:13
    container_name: auth_db
    environment:
      POSTGRES_DB: auth_service_db
      POSTGRES_USER: auth_service_user
      POSTGRES_PASSWORD: password
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_service_user -d auth_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  
  user_service:
    build:
      context: ./back/user_service
    container_name: user-service
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DB_HOST: user_db
      DB_PORT: 5432
      DB_NAME: user_service_db
      DB_USER: user_service_user
      DB_PASSWORD: password
      SECRET_KEY: $SECRET_KEY
    volumes:
      - ./back/user_service:/app
      - media:/app/media
    ports:
      - '8001:8000'
    networks:
      - app_network
    depends_on:
      redis:
        condition: service_started
      user_db:
        condition: service_healthy

  user_db:
    image: postgres:13
    container_name: user_db
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: user_service_user
      POSTGRES_PASSWORD: password
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_service_user -d user_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  game_service:
    build:
      context: ./back/game_service
    container_name: game-service
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DB_HOST: game_db
      DB_PORT: 5432
      DB_NAME: game_service_db
      DB_USER: game_service_user
      DB_PASSWORD: password
      SECRET_KEY: $SECRET_KEY
    volumes:
      - ./back/game_service:/app
      - media:/app/media
    ports:
      - '8002:8000'
    networks:
      - app_network
    depends_on:
      redis:
        condition: service_started
      game_db:
        condition: service_healthy

  game_db:
    image: postgres:13
    container_name: game_db
    environment:
      POSTGRES_DB: game_service_db
      POSTGRES_USER: game_service_user
      POSTGRES_PASSWORD: password
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U game_service_user -d game_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5



  friend_service:
    build:
      context: ./back/friend_service
    container_name: friend-service
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DB_HOST: friend_db
      DB_PORT: 5432
      DB_NAME: friend_service_db
      DB_USER: friend_service_user
      DB_PASSWORD: password
      SECRET_KEY: $SECRET_KEY
    ports:
      - '8003:8000'
    volumes:
      - ./back/friend_service:/app
    networks:
      - app_network
    depends_on:
      redis:
        condition: service_started
      friend_db:
        condition: service_healthy

  friend_db:
    image: postgres:13
    container_name: friend_db
    environment:
      POSTGRES_DB: friend_service_db
      POSTGRES_USER: friend_service_user
      POSTGRES_PASSWORD: password
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U friend_service_user -d friend_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5


  mail_service:
    build:
      context: ./back/mail_service
    container_name: mail-service
    environment:
      EMAIL_HOST_USER: $EMAIL_HOST_USER
      EMAIL_HOST_PASSWORD: $EMAIL_HOST_PASSWORD
      CELERY_BROKER_URL: redis://redis:6379/0
    ports:
      - '8004:8000'
    volumes:
      - ./back/mail_service:/app
    networks:
      - app_network
    depends_on:
      redis:
        condition: service_started

  notification_service:
    build:
      context: ./back/notification_service
    container_name: notification-service
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
    ports:
      - '8005:8000'
    volumes:
      - ./back/notification_service:/app
    networks:
      - app_network
    depends_on:
      redis:
        condition: service_started


  chat_service:
    build:
      context: ./back/chat_service
    container_name: chat-service
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DB_HOST: chat_db
      DB_PORT: 5432
      DB_NAME: chat_service_db
      DB_USER: chat_service_user
      DB_PASSWORD: password
      SECRET_KEY: $SECRET_KEY
    ports:
      - '8006:8000'
    volumes:
      - ./back/chat_service:/app
    networks:
      - app_network
    depends_on:
      redis:
        condition: service_started
      chat_db:
        condition: service_healthy

  chat_db:
    image: postgres:13
    container_name: chat_db
    environment:
      POSTGRES_DB: chat_service_db
      POSTGRES_USER: chat_service_user
      POSTGRES_PASSWORD: password
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chat_service_user -d chat_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./nginx
      args:
        HOST_HOSTNAME: $HOST_HOSTNAME
    container_name: nginx
    environment:
      HOST_HOSTNAME: $HOST_HOSTNAME
    volumes:
      - ./front:/app
      - media:/usr/share/nginx/media
    ports:
      - '3000:80'
      - '5000:443'
    networks:
      - app_network
    depends_on:
      - chat_service
      - mail_service
      - user_service
      - notification_service


  front:
    build:
      context: ./front
    container_name: front
    networks:
      - app_network
    volumes:
      - ./front:/app



networks:
  app_network:
    driver: bridge

volumes:
  media: