# Generated by Django 4.2.16 on 2024-12-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='tournament_round',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
