# Generated by Django 4.2.16 on 2024-11-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmodel',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('started', 'Started'), ('finished', 'Finished')], default='waiting'),
        ),
    ]
